### ISSUE TITLE
It was very good, but Gmail changed something and now it doesn't work as it should.

### ISSUE THREAD

**Issue by ghost** [shellscape/gmail-classic#10]
- Browser Name and Version:
- gmail-classic Version:

### Screenshot of Problem

It was very good, but gmail changed something and now it doesn't work as it should.

**Comment by shellscape** [comment]
That's not a helpful issue. You haven't described what's broken, provided screenshots nor error information.

**Comment by ghost** [comment]
It's not very clear how to provide screenshots if the style doesn't work right now. The left column is stretched out, not compact.

![2020-08-08 17_29_40-Re_  shellscape_gmail-classic  It was very good, but Gmail changed something and](https://user-images.githubusercontent.com/12909450/89713009-45102400-d99d-11ea-92f7-6911a5c98ccd.jpg)
