### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by DexperienceIsTrashAtCSS** [shellscape/gmail-classic#13]
- Browser Name and Version: chrome for macOS idk version
- Gmail-classic Version:

### Expected Behavior
i used this in the past idk what happened

### Actual Behavior
slightle works but sidebar css not working ex. compose button

**Comment by shellscape** [comment]
Gmail probably updated again. I still use this and while there are some quirks it's fine for me. You're welcome to submit a PR with any fixes

**Comment by DexperienceIsTrashAtCSS** [comment]
nice thanks

**Comment by DexperienceIsTrashAtCSS** [comment]
fixed it by switching URL to URLs that start with
