### ISSUE TITLE
doesnt work ? 

### ISSUE THREAD

**Issue by yhhoenn** [shellscape/gmail-classic#3]
i dont know if im just stupid but nothing happened when i tried using it ?

**Comment by shellscape** [comment]
I'm using it with Stylus on three different systems with 5 different accounts. It most definitely does work. Probably an issue with the extension you've chosen to use the CSS with.

**Comment by yhhoenn** [comment]
Ok, I got it too work but the UI looks a bit weird

**Comment by shellscape** [comment]
Sorry you feel that way. Looks great to me :)

**Comment by veb** [comment]
I had to use the following URL: `https://mail.google.com/mail/u/0/#inbox` as I have multiple accounts as well. I can't just use `mail.google.com` - and selecting "url starts with" instead of just URL.

Anyways. Great work @shellscape 👍
